### PR TITLE
added service reload and reload command for systemd

### LINKED ISSUE #8: In case of systemd daemon-reload needs to be done
When changing the unit file for systemd on a running system you need to run daemon reload or it wont restart the service.

The systemd_unit resource does that automatically. But using it would break the modularity implemented here. 
My current workaround is adding a reload notify to the resource and a reload command in an if statement(to check if systemd) on the service. But i dont know if that breaks compatability with upstart or sysv.

### PR DESCRIPTION
**Pull request by elouin**
Resolves https://github.com/dhoer/chef-xvfb/issues/8

### CODE REVIEW

**Comment by dhoer** [comment]
Thanks for the pull request. Would you be interested in taking ownership of this cookbook?

**Comment by elouin** [comment]
Sorry for the very delayed answer. I had to rule out some organisational things.

I would like to take the ownership of this cookbook, if your offer still stands.

**Comment by dhoer** [comment]
Thanks for volunteering to maintain this cookbook.  

I tried to transfer ownership, but it says you have a repo with that name already.  Can you please rename that repo and let me know so I can complete the transfer?

**Comment by elouin** [comment]
Renamed it.

**Comment by dhoer** [comment]
Not sure what this error message means:
elouin already has a repository in the dhoer/chef-xvfb network

**Pull request merged**
